config/routes.rb
Rails.application.routes.draw do
  get '/top' => 'books#top'
  root :to => 'books#top'
  get 'books' => 'books#index', as: 'index_book'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/edit' => 'books#edit'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
validates :title, presence: true
validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
      @books = Book.all
      render :index
    end
  end


  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
       render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])# データ（レコード）を1件取得
    book.destroy # データ（レコード）を削除
    redirect_to '/books', notice: "Book was successfully destroyed."# 投稿一覧画面へリダイレクト
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id),method: :patch do |f| %>
  <h5>Title</h5>
  <%= f.text_field :title %>
  <h5>Body</h5>
  <%= f.text_area :body %>
  </br>

  <%= f.submit 'Update Book'%>
  </br>

  <%= link_to "Show", Book.find(params[:id]) %>
  |
  <%= link_to "Back", "/books" %>
<% end %>

app/views/books/index.html.erb
<p id="notice">
 <%=  notice %>
</p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
     <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id) %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>

     <% end %>
  </tbody>
</table>


<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do |f| %>

    <%= f.label :Title %><br/>
    <%= f.text_field :title%>



    <%= f.label :Body %><br/>
    <%= f.text_area :body%>

    </br>

   <%= f.submit 'Create Book' %>
<% end %>
</form>

app/views/books/show.html.erb
<p id="notice">
 <%=  notice %>
</p>

<h4>Title:</h4>
<p><%= @book.title %></p>

<h4>Body:</h4>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book) %>
|
<%= link_to "Back", "/books" %>

app/views/books/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！
</h1>
<p><strong>Bookers</strong>
では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<%= link_to 'Start', index_book_path(@book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>